name: Prisma Baseline (one-time)

on:
  workflow_dispatch:

jobs:
  baseline:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Generate Prisma Client
        run: npx prisma generate --schema prisma/schema.prisma

      - name: Mark baseline migration as applied
        run: npx prisma migrate resolve --applied 000_init --schema prisma/schema.prisma
