name: Prisma Baseline (one-time)
on:
  workflow_dispatch: {}

jobs:
  baseline:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4

      # No cache here (it requires a lockfile). Also switch to `npm install`.
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --no-audit --no-fund
      - run: npx prisma generate

      # Mark ONLY the baseline as applied (no schema change).
      - run: npx prisma migrate resolve --applied 000_init
